MERGE_MAP = {
    "golf": "sports",
    "dictionaries":"reference",
    "quilts and quilting":"crafts and hobbies",
    "halloween":"holidays and celebrations",
    "cultural heritage":"ethnic studies",
    "popular culture":"entertainment and performing arts",
    "desserts":"cooking",
    "personal memoirs":"biography and autobiography",
    "sociology":"social sciences",
    "pets":"animals",
    "trivia":"games and activities",
    "suspense":"thrillers",
    "teaching methods and materials":"education",
    "physics":"science and nature",
    "stress management":"self-help",
    "study aids":"education",
    "personal growth":"inspiration and personal growth",
    "study guides":"education",
    "school and education":"education",
    "programming languages":"technology and engineering",
    "presidents and heads of state":"history",
    "monkeys":"animals",
    "remodeling and renovation":"house and home",
    "infants and toddlers":"family and relationships",
    "new testament":"religion",
    "psychological":"psychology",
    "sewing":"crafts and hobbies",
    "self-esteem and self-reliance":"self-help",
    "self-management":"self-help",
    "psychopathology":"psychology",
    "anthropology": "history",
    "public policy":"politics",
    "psychotherapy":"psychology",
    "siblings":"family and relationships",
    "motherhood":"family and relationships",
    "horses":"animals",
    "nonfiction": "non-fiction",
    "international relations":"politics",
    "human resources and personnel management":"business and economics",
    "economics":"business and economics",
    "writing skills": "writing",
    "running and jogging":"sports",
    "humorous": "humor",
    "motivational and inspirational": "inspiration and personal growth",
    "decorating":"house and home",
    "computers":"technology and engineering",
    "historical": "history",
    "design":"art",
    "personal finance":"business and economics",
    "diseases":"medical",
    "environmental conservation and protection":"science and nature",
    "emotions and feelings":"psychology",
    "history & theory": "history",
    "film":"entertainment and performing arts",
    "hard-boiled":"cooking",
    "love and romance": "family and relationships",
    "action": "action and adventure",
    "african american studies": "ethnic studies",
    "african american":"ethnic studies",
    "american government": "politics",
    "state and local":"politics",
    "biographical": "biography and autobiography",
    "autobiographical": "biography and autobiography",
    "sports and recreation": "sports",
    "management":"business and economics",
    "marketing":"business and economics",
    "science": "science and nature",
    "mysteries & detective stories": "mystery",
    "marriage & long-term relationships": "marriage and family",
    "biography & autobiography": "biography and autobiography",
    "christian": "religion",
    "job hunting":"careers",
    "christian life": "religion",
    "christian living": "religion",
    "christianity":"religion",
    "christian ministry": "religion",
    "christian theology": "religion",
    "comic strips and cartoons": "comics and graphic novels",
    "composition and creative writing": "writing",
    "contemporary women": "girls and women",
    "courses and dishes": "cooking",
    "devotional": "religion",
    "easter and lent": "holidays and celebrations",
    "adventure":"action and adventure",
    "espionage":"action and adventure",
    "beverages":"cooking",
    "alcoholic":"cooking",
    "vegetables":"cooking",
    "internet":"technology and engineering",
    "aviation":"transportation",
    "colonial and revolutionary periods":"history",
    "cats":"animals",
    "fables":"fairy tales and folklore",
    "family":"family and relationships",
    "family life":"family and relationships",
    "fatherhood": "family and relationships",
    "games": "games and activities",
    "toys":"games and activities",
    "puzzles":"games and activities",
    "activity books": "games and activities",
    "bereavement": "grief",
    "real estate":"house and home",
    "holiday":"holidays and celebrations",
    "humor story":"humor",
    "legal":"law",
    "judaism":"religion",
    "jokes and riddles":"humor",
    "inspirational": "inspiration and personal growth",
    "healing": "health and fitness",
    "health and daily living": "health and fitness",
    "health and fitness": "health and fitness",
    "language arts and disciplines":"language arts",
    "health and healing": "health and fitness",
    "weight control":"health and fitness",
    "healthy living": "health and fitness",
    "exercise":"health and fitness",
    "investments and securities":"business and economics",
    "investing":"business and economics",
    "religious":"religion",
    "life sciences":"science and nature",
    "dogs":"animals",
    "apes":"animals",
    "flowers":"gardening",
    "baseball":"sports",
    "basketball":"sports",
    "biblical studies":"religion",
    "breeds":"animals",
    "women":"girls and women",
    "chapter books":"juvenile fiction",
    "women s health":"girls and women",
    "ethics and moral philosophy":"philosophy",
    "christmas and advent":"holidays and celebrations",
    "women s studies": "girls and women",
    "essays and travelogues": "travel",
    "erotica":"romance",
    "women sleuths":"mystery",
    "low fat":"diet and nutrition",
    "political":"politics",
    "social science":"social sciences",
    "nutrition":"diet and nutrition",
    "political ideologies":"politics",
    "mystery and detective":"mystery",
    "mystery and detective story":"mystery",
    "political process":"politics",
    "performing arts":"entertainment and performing arts",
    "do-it-yourself":"crafts and hobbies",
    "counting and numbers":"mathematics",
    "conservatism and liberalism":"politics",
    "political science":"politics",
    "campaigns and elections":"politics",
    "catholic":"religion",
    "world war ii":"war and military",
    "terrorism":"war and military",
    "diets":"diet and nutrition",
    "vegetarian":"diet and nutrition",
    "television":"entertainment and performing arts",
    "spirituality":"religion",
    "specific ingredients":"cooking",
    "space opera":"science fiction",
    "civil war period":"history",
    "literary collections":"literary",
    "literary figures":"literary",
    "operating systems":"technology and engineering",
    "literary criticism":"literary",
    "nature":"science and nature",
    "needlework":"crafts and hobbies",
    "papercrafts":"crafts and hobbies",
    "nursing":"medical",
    "marriage and long-term relationships":"family and relationships",
    "marriage and family":"family and relationships",
    "football":"sports",
    "military":"war and military",
    "history and theory":"history",
    "astronomy":"science and nature",
    "earth sciences":"science and nature",
    "parenting":"family and relationships",
    "fantasy and magic":"fantasy",
    "police procedural":"thrillers",
    "myths":"fairy tales and folklore",
    "humorous story":"humor",
    "parents":"family and relationships"
}

US_STATE_ABBRS = {
    "al","ak","az","ar","ca","co","ct","de","fl","ga","hi","id","il","in","ia","ks","ky",
    "la","me","md","ma","mi","mn","ms","mo","mt","ne","nv","nh","nj","nm","ny","nc","nd",
    "oh","ok","or","pa","ri","sc","sd","tn","tx","ut","vt","va","wa","wv","wi","wy","dc"
}

DROP_LABELS = {
    "etc.", "etc", "form", "topic", "topics", "beginner", "intermediate","hardware","body","fiction","interpersonal relations","friendship",
    "advanced", "english", "american", "european", "italian", "french","traditional","death","happiness","infants and toddlers","cleaning",
    "irish", "scottish", "welsh", "europe", "asia", "south", "west", "world","leadership","legends","royalty","pacific ak","sagas","social themes","social topics",
    "seasonal", "contemporary", "developmental", "development", "methods","irish","italy","short story","shakespeare","people and places","personal and practical guides",
    "techniques", "special interest", "subjects & themes", "genres & styles","success","traditional","caretaking and organizing","security","antiques and collectibles",
    "people & places", "new experience", "northeast", "middle east","concepts","essays","ancient and classical","bedtime and dreams","anthologies",
    "great britain", "united states","entertaining", "epic", "saga","france","regency","readers","quotations","subjects and themes","media tie-in",
    "quick and easy","19th century","20th century","genres and styles","international","south atlantic dc","life stages","regional and ethnic"
}